apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: pilchfish/docker-nginx-proxy
    newTag: arm64
patches:
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
