apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx-proxy
          image: pilchfish/docker-nginx-proxy:arm64
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: PROXY_TARGET
              value: "http://gateway:8080"